batch_size: 2  # Batch size for training
learning_rate: 0.001  # Learning rate for the optimizer
epochs: 10  # Number of training epochs
log_interval: 100  # Interval (in batches) at which to log training metrics
log_dir: "logs"  # Directory where TensorBoard logs will be saved
anneal_function: "logistic"  # Annealing function for KL divergence weight ('logistic' or 'linear')
k: 0.0025  # k value for the annealing function
annealing_till: 2500  # Number of steps for full annealing
